<?xml version="1.0" encoding="UTF-8"?>
<tileset name="creep1_grunt" tilewidth="72" tileheight="72">
 <properties>
  <property name="health_point" value="100"/>
  <property name="name" value="Grunt"/>
 </properties>
 <image source="../textures/warcraft2/orc/units/grunt.png" trans="ff00ff" width="360" height="864"/>
 <terraintypes>
  <terrain name="idle_up" tile="0"/>
  <terrain name="idle_up_right" tile="1"/>
  <terrain name="idle_right" tile="2"/>
  <terrain name="idle_down_right" tile="3"/>
  <terrain name="idle_down" tile="4"/>
  <terrain name="walk1_up" tile="10"/>
  <terrain name="walk2_up" tile="5"/>
  <terrain name="walk3_up" tile="10"/>
  <terrain name="walk4_up" tile="20"/>
  <terrain name="walk5_up" tile="15"/>
  <terrain name="walk6_up" tile="20"/>
  <terrain name="walk1_up_right" tile="11"/>
  <terrain name="walk2_up_right" tile="6"/>
  <terrain name="walk3_up_right" tile="11"/>
  <terrain name="walk4_up_right" tile="21"/>
  <terrain name="walk5_up_right" tile="16"/>
  <terrain name="walk6_up_right" tile="21"/>
  <terrain name="walk1_right" tile="12"/>
  <terrain name="walk2_right" tile="7"/>
  <terrain name="walk3_right" tile="12"/>
  <terrain name="walk4_right" tile="22"/>
  <terrain name="walk5_right" tile="17"/>
  <terrain name="walk6_right" tile="22"/>
  <terrain name="walk1_down_right" tile="13"/>
  <terrain name="walk2_down_right" tile="8"/>
  <terrain name="walk3_down_right" tile="13"/>
  <terrain name="walk4_down_right" tile="23"/>
  <terrain name="walk5_down_right" tile="18"/>
  <terrain name="walk6_down_right" tile="23"/>
  <terrain name="walk1_down" tile="14"/>
  <terrain name="walk2_down" tile="9"/>
  <terrain name="walk3_down" tile="14"/>
  <terrain name="walk4_down" tile="24"/>
  <terrain name="walk5_down" tile="19"/>
  <terrain name="walk6_down" tile="24"/>
  <terrain name="attack1_up" tile="25"/>
  <terrain name="attack2_up" tile="30"/>
  <terrain name="attack3_up" tile="35"/>
  <terrain name="attack4_up" tile="40"/>
  <terrain name="attack1_up_right" tile="26"/>
  <terrain name="attack2_up_right" tile="31"/>
  <terrain name="attack3_up_right" tile="36"/>
  <terrain name="attack4_up_right" tile="41"/>
  <terrain name="attack1_right" tile="27"/>
  <terrain name="attack2_right" tile="32"/>
  <terrain name="attack3_right" tile="37"/>
  <terrain name="attack4_right" tile="42"/>
  <terrain name="attack1_down_right" tile="28"/>
  <terrain name="attack2_down_right" tile="33"/>
  <terrain name="attack3_down_right" tile="38"/>
  <terrain name="attack4_down_right" tile="43"/>
  <terrain name="attack1_down" tile="29"/>
  <terrain name="attack2_down" tile="34"/>
  <terrain name="attack3_down" tile="39"/>
  <terrain name="attack4_down" tile="44"/>
  <terrain name="death1_up" tile="45"/>
  <terrain name="death2_up" tile="50"/>
  <terrain name="death3_up" tile="55"/>
  <terrain name="death1_up_right" tile="46"/>
  <terrain name="death2_up_right" tile="51"/>
  <terrain name="death3_up_right" tile="56"/>
  <terrain name="death1_right" tile="47"/>
  <terrain name="death2_right" tile="52"/>
  <terrain name="death3_right" tile="57"/>
  <terrain name="death1_down_right" tile="48"/>
  <terrain name="death2_down_right" tile="53"/>
  <terrain name="death3_down_right" tile="58"/>
  <terrain name="death1_down" tile="49"/>
  <terrain name="death2_down" tile="54"/>
  <terrain name="death3_down" tile="59"/>
 </terraintypes>
</tileset>
