// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Proto.proto

package protobuf;

/**
 * Protobuf enum {@code protobuf.Action}
 */
public enum Action
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLAYER_CREATE = 0;</code>
   */
  PLAYER_CREATE(0),
  /**
   * <code>PLAYER_MOVE = 1;</code>
   */
  PLAYER_MOVE(1),
  /**
   * <code>PLAYER_REMOVE = 2;</code>
   */
  PLAYER_REMOVE(2),
  /**
   * <code>OBJECT_CREATE = 3;</code>
   */
  OBJECT_CREATE(3),
  /**
   * <code>OBJECT_MOOVE = 4;</code>
   */
  OBJECT_MOOVE(4),
  /**
   * <code>OBJECT_REMOVE = 5;</code>
   */
  OBJECT_REMOVE(5),
  /**
   * <code>MAP_INIT = 6;</code>
   */
  MAP_INIT(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PLAYER_CREATE = 0;</code>
   */
  public static final int PLAYER_CREATE_VALUE = 0;
  /**
   * <code>PLAYER_MOVE = 1;</code>
   */
  public static final int PLAYER_MOVE_VALUE = 1;
  /**
   * <code>PLAYER_REMOVE = 2;</code>
   */
  public static final int PLAYER_REMOVE_VALUE = 2;
  /**
   * <code>OBJECT_CREATE = 3;</code>
   */
  public static final int OBJECT_CREATE_VALUE = 3;
  /**
   * <code>OBJECT_MOOVE = 4;</code>
   */
  public static final int OBJECT_MOOVE_VALUE = 4;
  /**
   * <code>OBJECT_REMOVE = 5;</code>
   */
  public static final int OBJECT_REMOVE_VALUE = 5;
  /**
   * <code>MAP_INIT = 6;</code>
   */
  public static final int MAP_INIT_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Action valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Action forNumber(int value) {
    switch (value) {
      case 0: return PLAYER_CREATE;
      case 1: return PLAYER_MOVE;
      case 2: return PLAYER_REMOVE;
      case 3: return OBJECT_CREATE;
      case 4: return OBJECT_MOOVE;
      case 5: return OBJECT_REMOVE;
      case 6: return MAP_INIT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Action>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Action> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Action>() {
          public Action findValueByNumber(int number) {
            return Action.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return protobuf.Protobuf.getDescriptor().getEnumTypes().get(0);
  }

  private static final Action[] VALUES = values();

  public static Action valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protobuf.Action)
}

