// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Proto.proto

package protobuf;

public interface ObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Object)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>.protobuf.Action action = 3;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.protobuf.Action action = 3;</code>
   * @return The action.
   */
  protobuf.Action getAction();

  /**
   * <code>string prefabName = 4;</code>
   * @return The prefabName.
   */
  java.lang.String getPrefabName();
  /**
   * <code>string prefabName = 4;</code>
   * @return The bytes for prefabName.
   */
  com.google.protobuf.ByteString
      getPrefabNameBytes();

  /**
   * <code>.protobuf.Object.Color color = 5;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>.protobuf.Object.Color color = 5;</code>
   * @return The color.
   */
  protobuf.Object.Color getColor();
  /**
   * <code>.protobuf.Object.Color color = 5;</code>
   */
  protobuf.Object.ColorOrBuilder getColorOrBuilder();

  /**
   * <code>repeated .protobuf.Object object = 6;</code>
   */
  java.util.List<protobuf.Object> 
      getObjectList();
  /**
   * <code>repeated .protobuf.Object object = 6;</code>
   */
  protobuf.Object getObject(int index);
  /**
   * <code>repeated .protobuf.Object object = 6;</code>
   */
  int getObjectCount();
  /**
   * <code>repeated .protobuf.Object object = 6;</code>
   */
  java.util.List<? extends protobuf.ObjectOrBuilder> 
      getObjectOrBuilderList();
  /**
   * <code>repeated .protobuf.Object object = 6;</code>
   */
  protobuf.ObjectOrBuilder getObjectOrBuilder(
      int index);

  /**
   * <code>.protobuf.Object.Transform transform = 7;</code>
   * @return Whether the transform field is set.
   */
  boolean hasTransform();
  /**
   * <code>.protobuf.Object.Transform transform = 7;</code>
   * @return The transform.
   */
  protobuf.Object.Transform getTransform();
  /**
   * <code>.protobuf.Object.Transform transform = 7;</code>
   */
  protobuf.Object.TransformOrBuilder getTransformOrBuilder();

  /**
   * <code>repeated .protobuf.Object.Position position = 8;</code>
   */
  java.util.List<protobuf.Object.Position> 
      getPositionList();
  /**
   * <code>repeated .protobuf.Object.Position position = 8;</code>
   */
  protobuf.Object.Position getPosition(int index);
  /**
   * <code>repeated .protobuf.Object.Position position = 8;</code>
   */
  int getPositionCount();
  /**
   * <code>repeated .protobuf.Object.Position position = 8;</code>
   */
  java.util.List<? extends protobuf.Object.PositionOrBuilder> 
      getPositionOrBuilderList();
  /**
   * <code>repeated .protobuf.Object.Position position = 8;</code>
   */
  protobuf.Object.PositionOrBuilder getPositionOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.Object.Rotation rotation = 9;</code>
   */
  java.util.List<protobuf.Object.Rotation> 
      getRotationList();
  /**
   * <code>repeated .protobuf.Object.Rotation rotation = 9;</code>
   */
  protobuf.Object.Rotation getRotation(int index);
  /**
   * <code>repeated .protobuf.Object.Rotation rotation = 9;</code>
   */
  int getRotationCount();
  /**
   * <code>repeated .protobuf.Object.Rotation rotation = 9;</code>
   */
  java.util.List<? extends protobuf.Object.RotationOrBuilder> 
      getRotationOrBuilderList();
  /**
   * <code>repeated .protobuf.Object.Rotation rotation = 9;</code>
   */
  protobuf.Object.RotationOrBuilder getRotationOrBuilder(
      int index);

  /**
   * <code>repeated .protobuf.Object.Scale scale = 10;</code>
   */
  java.util.List<protobuf.Object.Scale> 
      getScaleList();
  /**
   * <code>repeated .protobuf.Object.Scale scale = 10;</code>
   */
  protobuf.Object.Scale getScale(int index);
  /**
   * <code>repeated .protobuf.Object.Scale scale = 10;</code>
   */
  int getScaleCount();
  /**
   * <code>repeated .protobuf.Object.Scale scale = 10;</code>
   */
  java.util.List<? extends protobuf.Object.ScaleOrBuilder> 
      getScaleOrBuilderList();
  /**
   * <code>repeated .protobuf.Object.Scale scale = 10;</code>
   */
  protobuf.Object.ScaleOrBuilder getScaleOrBuilder(
      int index);
}
