// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Proto.proto

package protobuf;

public interface ProtoObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.ProtoObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>.protobuf.Action action = 3;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.protobuf.Action action = 3;</code>
   * @return The action.
   */
  protobuf.Action getAction();

  /**
   * <code>string prefabName = 4;</code>
   * @return The prefabName.
   */
  java.lang.String getPrefabName();
  /**
   * <code>string prefabName = 4;</code>
   * @return The bytes for prefabName.
   */
  com.google.protobuf.ByteString
      getPrefabNameBytes();

  /**
   * <code>.protobuf.ProtoObject.Color color = 5;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>.protobuf.ProtoObject.Color color = 5;</code>
   * @return The color.
   */
  protobuf.ProtoObject.Color getColor();
  /**
   * <code>.protobuf.ProtoObject.Color color = 5;</code>
   */
  protobuf.ProtoObject.ColorOrBuilder getColorOrBuilder();

  /**
   * <code>.protobuf.ProtoObject.Transform transform = 6;</code>
   * @return Whether the transform field is set.
   */
  boolean hasTransform();
  /**
   * <code>.protobuf.ProtoObject.Transform transform = 6;</code>
   * @return The transform.
   */
  protobuf.ProtoObject.Transform getTransform();
  /**
   * <code>.protobuf.ProtoObject.Transform transform = 6;</code>
   */
  protobuf.ProtoObject.TransformOrBuilder getTransformOrBuilder();

  /**
   * <code>repeated .protobuf.ProtoObject protoObjects = 7;</code>
   */
  java.util.List<protobuf.ProtoObject> 
      getProtoObjectsList();
  /**
   * <code>repeated .protobuf.ProtoObject protoObjects = 7;</code>
   */
  protobuf.ProtoObject getProtoObjects(int index);
  /**
   * <code>repeated .protobuf.ProtoObject protoObjects = 7;</code>
   */
  int getProtoObjectsCount();
  /**
   * <code>repeated .protobuf.ProtoObject protoObjects = 7;</code>
   */
  java.util.List<? extends protobuf.ProtoObjectOrBuilder> 
      getProtoObjectsOrBuilderList();
  /**
   * <code>repeated .protobuf.ProtoObject protoObjects = 7;</code>
   */
  protobuf.ProtoObjectOrBuilder getProtoObjectsOrBuilder(
      int index);

  /**
   * <code>.protobuf.ProtoObject.Position position = 8;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.protobuf.ProtoObject.Position position = 8;</code>
   * @return The position.
   */
  protobuf.ProtoObject.Position getPosition();
  /**
   * <code>.protobuf.ProtoObject.Position position = 8;</code>
   */
  protobuf.ProtoObject.PositionOrBuilder getPositionOrBuilder();

  /**
   * <code>.protobuf.ProtoObject.Rotation rotation = 9;</code>
   * @return Whether the rotation field is set.
   */
  boolean hasRotation();
  /**
   * <code>.protobuf.ProtoObject.Rotation rotation = 9;</code>
   * @return The rotation.
   */
  protobuf.ProtoObject.Rotation getRotation();
  /**
   * <code>.protobuf.ProtoObject.Rotation rotation = 9;</code>
   */
  protobuf.ProtoObject.RotationOrBuilder getRotationOrBuilder();

  /**
   * <code>.protobuf.ProtoObject.Scale scale = 10;</code>
   * @return Whether the scale field is set.
   */
  boolean hasScale();
  /**
   * <code>.protobuf.ProtoObject.Scale scale = 10;</code>
   * @return The scale.
   */
  protobuf.ProtoObject.Scale getScale();
  /**
   * <code>.protobuf.ProtoObject.Scale scale = 10;</code>
   */
  protobuf.ProtoObject.ScaleOrBuilder getScaleOrBuilder();
}
